jobproject/jobapp/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from .views import JobUpdateView, job_list
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    
    path('', views.index, name='index'),
    path('admin_home',views.admin_home,name='adminhome'),
    path('admin_applicants',views.admin_applicantsview,name='adminapplicants'),
    path('admin_companies',views.admin_companiesview,name='admincompanies'),
    path('admin_users',views.admin_usersview,name='allusers'),
    path('applicantogin',views.applicantlogin_view,name='applicantlogin'),
    path('companylogin',views.companylogin_view,name='companylogin'),
    path('sign_up', views.signup_view, name='sign_up'), 
    path('Logout/', views.logout_view, name='Logout'),
    path('reset',views.resetPassword,name='reset'),
    path('applicantform',views.applicant_form_view,name='applicantform'),
    path('companyform',views.company_form_view, name='companyform'),
    path('companyhome', views.company_home, name='companyhome'),
    path('applicant/<int:id>/', views.applicant_details, name='applicant_details'),
    path('companies_jobs/',views.companies_with_jobs, name='companiesjobs'),
    path('applicanthome', views.applicant_home, name='applicanthome'),
    path('job/<int:id>/', views.job_details, name='job_details'),
    path('applicantprofile', views.applicantprofile_view, name='applicantprofile'),
    path('companyprofile', views.companyprofile_view, name='companyprofile'),
    path('postjob',views.post_job_view,name='postjob'),
    path('joblist', views.job_list, name='joblist'),
    path('companyjobs', views.company_jobs_list, name='companyjobs'),
    path('company/<int:company_id>/jobs/', views.view_jobs, name='view_jobs'),
    path('joblist/delete/<int:job_id>/', views.delete_job_view, name='delete_job'),
    path('joblist/edit/<int:pk>/', JobUpdateView.as_view() , name='edit_job'),
    path('apply/<int:job_id>/', views.applyjob_view, name='apply_job'),
    path('my-applied-jobs/', views.applicant_jobs_view, name='appliedjobs'),
    path('viewapplicants', views.view_applicants, name='viewapplicants'),
    path('searchjobs', views.search_jobs, name='searchjobs'),
    path('searchapplicants', views.search_applicants, name='searchapplicants'),
    path('errorcomp',views.errorcomp_view,name='errorcomp'),
    path('errorappl',views.errorappl_view,name='errorappl'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('aboutus1', views.aboutus_view1, name='aboutus1'),
    path('contactus1/', views.contactus_view1, name='contactus1'),
    path('aboutus2', views.aboutus_view2, name='aboutus2'),
    path('contactus2/', views.contactus_view2, name='contactus2'),
    
]

#+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

 

jobproject/jobproject/urls.py
from django.contrib import admin
from django.urls import path,include
from jobapp.views import*
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls,name='adminview'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',include('jobapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header="JOB PERFECTS ADMINISTRATION"

jobproject/jobapp/models.py
from django.contrib.auth.models import User
from django.db import models

    
class Applicant(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    age=models.IntegerField()
    gender=models.CharField(max_length=10,choices=[('gen_male','M'),('gen_female','F')],default='gen_male')
    phone_number=models.CharField(max_length=15,null=True)
    qualification=models.CharField(max_length=100,default="")
    year_of_experience=models.IntegerField(default=0)
    job_title=models.CharField(max_length=25,blank=True,null=True)
    location=models.CharField(max_length=20,blank=True,null=True)
    resume=models.FileField(null=True,blank=True)
    
    
    def __str__(self):
        return self.name
    
class Company(models.Model):
    name = models.CharField(max_length=255)
    info = models.TextField()
    email =models.EmailField(max_length=50)
    location = models.CharField(max_length=25)
    website = models.URLField(null=True, blank=True)
    type=models.CharField(max_length=20)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name  

class Job(models.Model):
    creator=models.ForeignKey(User,on_delete=models.CASCADE)
    company_name = models.ForeignKey(Company,on_delete=models.CASCADE)
    company_info = models.TextField()
    title= models.CharField(max_length=255)
    description=models.TextField()
    location = models.CharField(max_length=255)
    employment_type = models.CharField(max_length=50, choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract')],default='FT')
    date_posted = models.DateTimeField(auto_now_add=True)
    application_deadline = models.DateField()
    no_of_vacancy=models.IntegerField(default=0,blank=True,null=True)
    category=models.CharField(max_length=255)
    salary = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    qualification=models.CharField(max_length=100)
    experience_years=models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    

class ApplicantTracking(models.Model):
     STATUS_CHOICES = [
        ('applied', 'Applied'),
        ('interview', 'Interview'),
        ('offered', 'Offered'),
        ('rejected', 'Rejected')
    ]
     company=models.ForeignKey(Company,on_delete=models.CASCADE)
     jobs=models.ForeignKey(Job,on_delete=models.CASCADE)
     applicant=models.ForeignKey(Applicant,on_delete=models.CASCADE)
     application_status=models.CharField(max_length=255,choices=STATUS_CHOICES, default='applied')
     applied_date=models.DateTimeField(auto_now_add=True)
     resume=models.FileField()
     cover_letter=models.FileField(null=True,blank=True)

     def __str__(self):
        return f'{self.applicant}'

jobproject/jobapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .import models
from .models import Company
from .models import ApplicantTracking
from .models import Applicant
from .models import Job



class ApplicantForm(forms.ModelForm):
   
    class Meta:
        model = Applicant
        fields = [
            'name', 'age', 'gender', 'phone_number', 
            'qualification', 'year_of_experience','job_title','location','resume'
        ]
        widgets = {
            'gender': forms.RadioSelect(choices=[('gen_male', 'Male'), ('gen_female', 'Female')]),
            'job_title': forms.TextInput(attrs={'placeholder': 'Looking for the job'}),
        
        }


class JobForm(forms.ModelForm):
    CATEGORY_CHOICES = [
        ('IT', 'Information Technology (IT)'),('Healthcare', 'Healthcare'),('Finance', 'Finance'),
        ('Education', 'Education'),('Manufacturing', 'Manufacturing'),('Retail', 'Retail'),
        ('Transportation', 'Transportation'),('Construction', 'Construction'),
        ('Real_Estate', 'Real Estate'),('Hospitality', 'Hospitality'),
        ('Media_Entertainment', 'Media and Entertainment'),('Energy', 'Energy')
        ,('Telecommunications', 'Telecommunications'),('Agriculture', 'Agriculture'),
        ('Aerospace', 'Aerospace'),('Automotive', 'Automotive'),('Biotechnology', 'Biotechnology'),
        ('Consulting', 'Consulting'),('Food_Beverage', 'Food and Beverage'), ('Legal_Services', 'Legal Services'),
    ]
   
    category = forms.ChoiceField(choices=CATEGORY_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
   
    class Meta:
        model = Job
        fields = [
            'company_info','title','description','location','employment_type','application_deadline','category','salary','qualification','experience_years','no_of_vacancy'
        ]
        widgets = {
            'application_deadline': forms.DateInput(attrs={'type': 'date'}),
            'salary': forms.NumberInput(attrs={'step': 0.01}),
        }

class CompanyForm(forms.ModelForm):
    TYPE_CHOICES = [
        ('IT', 'Information Technology (IT)'),('Healthcare', 'Healthcare'),('Finance', 'Finance'),('Education', 'Education'),
        ('Manufacturing', 'Manufacturing'),('Retail', 'Retail'),('Transportation', 'Transportation'),('Construction', 'Construction'),
        ('Real_Estate', 'Real Estate'),('Hospitality', 'Hospitality'),('Media_Entertainment', 'Media and Entertainment'),('Energy', 'Energy'),
        ('Telecommunications', 'Telecommunications'), ('Agriculture', 'Agriculture'),('Aerospace', 'Aerospace'), ('Automotive', 'Automotive'),
        ('Biotechnology', 'Biotechnology'), ('Consulting', 'Consulting'),('Food_Beverage', 'Food and Beverage'),('Legal_Services', 'Legal Services'),
    ]
    type = forms.ChoiceField(choices=TYPE_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    info = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 10,'cols':10}))  # Adjust rows as needed
    class Meta:
        model = Company
        fields = ['name', 'info', 'email', 'location', 'website', 'type']


class ApplicantTrackingForm(forms.ModelForm):
    class Meta:
        model = ApplicantTracking
        fields = ['resume', 'cover_letter']
    

class ContactusForm(forms.Form):
    Name = forms.CharField(max_length=30)
    Email = forms.EmailField()
    Message = forms.CharField(max_length=500,widget=forms.Textarea(attrs={'rows': 5, 'cols': 30}))

jobproject/templates/aboutus.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us - Job Perfects</title>
    <link rel="stylesheet" href="{% static 'css/aboutus.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .navbar-custom {
    background-color: #1199b7;
}
body {
            background-image: url("{% static 'images/bgimage1.jpg' %}");
            background-size: cover; /* Make sure the image covers the entire background */
            background-position: center; /* Center the background image */
            background-repeat: no-repeat; /* Prevent the background from repeating */
            height: 200vh; /* Make sure the background covers the full height of the viewport */
            color: black; /* Set default text color to white */
        }
    </style>
</head>
<body>
    
        <nav class="navbar navbar-expand-md navbar-dark navbar-custom">
            <a href="/" class="navbar-brand">JOB PERFECTS</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto"> <!-- Changed ml-auto to mr-auto to align left -->
                    <li class="nav-item">
                        <a href="{% url 'index' %}" class="nav-link">HOME</a>
                    </li>
                    
                </ul>
            </div>
        </nav>
    <div class="container">
        <h1>Welcome to Job Perfects!</h1>
        <p>Your Perfect Job Awaits!</p>
        <p>At Job Perfects, we believe in connecting talented individuals with their dream jobs. Whether you are seeking your first job, looking to make a career change, or aiming to climb the corporate ladder, Job Perfects is here to help you every step of the way.</p>
        <h2>Why Choose Job Perfects?</h2>
        <ul>
            <li><strong>Comprehensive Job Listings</strong></li>
            <p>Thousands of job postings from leading companies across various industries. Regularly updated to ensure you have access to the latest opportunities.</p>
            <li><strong>Easy-to-Use Interface</strong></li>
            <p>Intuitive design for both job seekers and employers. Advanced search filters to help you find the perfect match quickly.</p>
            <li><strong>Personalized Job Recommendations</strong></li>
            <p>AI-driven algorithms to suggest jobs that fit your skills, experience, and career goals. Save your searches and receive notifications for new job postings.</p>
            <li><strong>Career Resources and Advice</strong></li>
            <p>Access to a wealth of resources including resume building tips, interview preparation guides, and career development articles. Webinars and workshops hosted by industry experts.</p>
            <li><strong>Employer Insights</strong></li>
            <p>Detailed company profiles to help you learn more about potential employers. Employee reviews and ratings to give you an inside look at company culture and work environment.</p>
            <li><strong>Secure and Confidential</strong></li>
            <p>Your privacy is our priority. We ensure that your personal information is protected and only shared with employers with your consent.</p>
        </ul>
        <h2>How It Works</h2>
        <h3>For Job Seekers:</h3>
        <ul>
            <li>Create a Profile - Sign up and create a detailed profile highlighting your skills, experience, and career aspirations.</li>
            <li>Search and Apply - Browse through job listings and apply to positions that interest you.</li>
            <li>Get Noticed - Employers can find and contact you directly through our platform.</li>
        </ul>
        <h3>For Employers:</h3>
        <ul>
            <li>Post a Job - Create job listings to attract top talent.</li>
            <li>Search Resumes - Access our database of qualified candidates.</li>
            <li>Hire the Best - Manage applications and streamline your hiring process with our easy-to-use tools.</li>
        </ul>
        <p class="text-center"><a href="{%url 'sign_up' %}" class="btn btn-primary">Join Job Perfects Today!</a></p>
        <p>Embark on your journey to career success with Job Perfects. Sign up now to start finding the job that is perfect for you.</p>
        <a href="{% url 'index' %}">Back to index page</a>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- Bootstrap JavaScript libraries -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  
</body>
</html>

jobproject/templates/adminapplicants.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Applicants</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/homestyles.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>

body {
    background-color: #f8f9fa;
    font-family: Arial, sans-serif;
}

.container {
    margin-top: 20px;
    padding: 20px;
    background-color: #ffffff;
    border-radius: 5px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

h1 {
    color: #1199b7;
    text-align: center;
    margin-bottom: 20px;
}

.table thead th {
    background-color: #1199b7;
    color: #ffffff;
    text-align: center;
}

.table tbody tr:nth-child(even) {
    background-color: #f2f2f2;
}

.form-control {
    width: auto;
    display: inline-block;
}

.btn-submit {
    background-color: #1199b7;
    color: #ffffff;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.btn-submit:hover {
    background-color: #0a6d91;
}


    </style>
</head>
<body>
    {% include "adminnavbar.html" %}
    
    <div class="container mt-5">
      <h1>Applicants</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Age</th>
                    <th>Gender</th>
                    <th>Phone Number</th>
                    <th>Qualification</th>
                    <th>Job title</th>
                    <th>Location</th>
                    <th>Resume</th>
                </tr>
            </thead>
            <tbody>
                {% for applicant in applicants %}
                    <tr>
                        <td>{{ applicant.name }}</td>
                        <td>{{ applicant.age }}</td>
                        <td>{{ applicant.get_gender_display  }}</td>
                        <td>{{ applicant.phone_number }}</td>
                        <td>{{ applicant.qualification }}</td>
                        <td>{{ applicant.job_title }}</td>
                        <td>{{ applicant.location }}</td>
                        <td>{{ applicant.applied_date }}</td>
                        <td><a href="{{ applicant.resume.url }}" class="btn btn-info btn-sm">View Resume</a></td>
                        
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

jobproject/templates/admincompanies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Companies</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/homestyles.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>

body {
    background-color: #f8f9fa;
    font-family: Arial, sans-serif;
}

.navbar-custom {
    background-color: #1199b7;
    position: fixed; 
    top: 0;          /* Position it at the very top */
        width: 100%;     /* Make the navbar stretch across the page */
        z-index: 1000;
}
.container {
    margin-top: 20px;
    padding: 20px;
    background-color: #ffffff;
    border-radius: 5px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

h1 {
    color: #1199b7;
    text-align: center;
    margin-bottom: 20px;
}

.table thead th {
    background-color: #1199b7;
    color: #ffffff;
    text-align: center;
}

.table tbody tr:nth-child(even) {
    background-color: #f2f2f2;
}

.form-control {
    width: auto;
    display: inline-block;
}

.btn-submit {
    background-color: #1199b7;
    color: #ffffff;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.btn-submit:hover {
    background-color: #0a6d91;
}


    </style>
</head>
<body>
    {% include "adminnavbar.html" %}
    
    <div class="container mt-5">
        <h1>Companies</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Information</th>
                    <th>Email</th>
                    <th>Location</th>
                    <th>Website</th>
                    <th>Type of Company</th>
                </tr>
            </thead>
            <tbody>
                {% for company in companies %}
                    <tr>
                        <td>{{ company.name }}</td>
                        <td>{{ company.info }}</td>
                        <td>{{ company.email }}</td>
                        <td>{{ company.location }}</td>
                        <td>{{ company.website }}</td>
                        <td>{{ company.type }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

jobproject/templates/apply_job.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apply for Job</title>
    <link rel="stylesheet" href="{% static 'css/applyjob.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
   
    <script src="{% static 'js/form.js' %}"></script>

</head>
<body>
    
    {% block content %}
    {% include 'applnavbar.html' %}
    
    <div class="container mt-5">
        <h2>Apply for Job</h2>
       
        <form method="post" id="Form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>
    {% endblock content %}
</body>
</html>

jobproject/templates/contactus.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .navbar-custom {
    background-color: #1199b7;
    }
    .btn.btn-primary {
        background-color: #1199b7;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
    }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark navbar-custom">
        <a href="/" class="navbar-brand">JOB PERFECTS</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto"> <!-- Changed ml-auto to mr-auto to align left -->
                <li class="nav-item">
                    <a href="{% url 'index' %}" class="nav-link">HOME</a>
                </li>
                
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        <h2>Contact Us</h2>
        <form method="post" id="Form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_Name">Name</label>
                {{ form.Name }}
            </div>
            <div class="form-group">
                <label for="id_Email">Email</label>
                {{ form.Email }}
            </div>
            <div class="form-group">
                <label for="id_Message">Message</label>
                {{ form.Message }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            document.getElementById('Form').addEventListener('submit', function(event) 
            {
              alert('Application submitted successfully');  
                 
            });
        });
      </script>
</body>
</html>

jobproject/templates/contactus1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .navbar-custom {
    background-color: #1199b7;
    }
    .btn.btn-primary {
        background-color: #1199b7;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
    }

    </style>
</head>
<body>
   {% include "applnavbar.html" %}
    <div class="container mt-5">
        <h2>Contact Us</h2>
        <form method="post" id="Form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_Name">Name</label>
                {{ form.Name }}
            </div>
            <div class="form-group">
                <label for="id_Email">Email</label>
                {{ form.Email }}
            </div>
            <div class="form-group">
                <label for="id_Message">Message</label>
                {{ form.Message }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            document.getElementById('Form').addEventListener('submit', function(event) 
            {
              alert('Application submitted successfully');  
                 
            });
        });
      </script>
</body>
</html>

jobproject/templates/contactus2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .navbar-custom {
    background-color: #1199b7;
    }
    .btn.btn-primary {
        background-color: #1199b7;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
    }
   
    </style>
</head>
<body>
    {% include "compnavbar.html" %}
    <div class="container mt-5">
        <h2>Contact Us</h2>
        <form method="post" id="Form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_Name">Name</label>
                {{ form.Name }}
            </div>
            <div class="form-group">
                <label for="id_Email">Email</label>
                {{ form.Email }}
            </div>
            <div class="form-group">
                <label for="id_Message">Message</label>
                {{ form.Message }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            document.getElementById('Form').addEventListener('submit', function(event) 
            {
              alert('Application submitted successfully');  
                 
            });
        });
      </script>
</body>
</html>

jobproject/templates/searchapplicants.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results</title>
    <link rel="stylesheet" href="{% static 'css/compstyle.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="{% static 'js/form.js' %}"></script>
</head>

<body>
    {% include "compnavbar.html" %}
    
<div class="container mt-5">
    <h2>Search Results</h2>
    {% if Applicants %}
        <ul class="list-group">
            {% for applicant in Applicants %}
                <li class="list-group-item">
                    <p><strong>Name:</strong> {{ applicant.name }}</p>
                    <p><strong>Age:</strong> {{ applicant.age }}</p>
                    <p><strong>Gender:</strong> {{ applicant.get_gender_display }}</p>
                    <p><strong>Phone:</strong> {{ applicant.phone_number }}</p>
                    <p><strong>Qualification:</strong> {{ applicant.qualification }}</p>
                    <p><strong>Year Of Experience:</strong> {{ applicant.year_of_experience }}</p>
                    <p><strong>Location:</strong> {{ applicant.location }}</p>
                    <p><strong>Preferred Job:</strong>{{applicant.job_title}}</p>
                    <p><strong>Resume:</strong>
                         {% if applicant.resume %}
                        <a href="{{ applicant.resume.url }}">Download Resume</a>
                        {% endif %}</p>
                    <h5>Do you want to contact {{ applicant.name }}?</h5>
                    <form action="" method="post" enctype="multipart/form-data" id="mailform">
                        {% csrf_token %}
                        <input type="hidden" name="applicant_id" value="{{ applicant.id }}">
                        <button type="submit" class="btn btn-primary">Send mail</button>
                    </form>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No applicants found matching your search criteria.</p>
    {% endif %}
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>

</html>